# Generated by Django 2.0.1 on 2019-04-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('day_of_birth', models.DateField(max_length=8)),
                ('current_city', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Persons',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
