# Generated by Django 2.0.1 on 2019-04-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_person_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='images/default_ava.png', upload_to='images'),
        ),
    ]
