# Generated by Django 2.0.1 on 2019-04-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190402_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='day_of_birth',
            new_name='date_of_birth',
        ),
    ]
